### ISSUE TITLE
Crash when mining Charged Certus Quartz Ore

### ISSUE THREAD

**Issue by JoeSGT** [xsun2001/Applied-Energistics-2-Unofficial#22]
Like the title mention you can crash when you have a pick and mine a block of Charged Certus Quartz Ore https://pastebin.com/raw/093n2VrF

**Comment by JoeSGT** [comment]
https://pastebin.com/raw/3fdppx5Q crash also  while trying to make pure fluix crystals it seem it's this commit that did the crash https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/d050451bce40c9a4c0f9f78117bb5215592bc950

**Comment by xsun2001** [comment]
Thanks for your reporting.

However, as you can see, this project isn't updated for a long time because I have to prepare for my Chinese College Entrance Examination and I seldom have time to look after it. I am ashamed of saying that but I couldn't give you much help right now. I am terribly sorry for that.

Back to your issue and I find that the commit https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/d050451bce40c9a4c0f9f78117bb5215592bc950 is ahead of the latest release version. If that is the case, please back to the version that is released or commit https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/4b0f540c8bfbf9a4dbf846d66b599270a18c7a33 . The commits behind that are simply a pile of cherry picks of the fixes in the origin repo. I have no time to test whether they work in 1.7.10 or whether they will cause something worse like crash. So please do not use it.

By the way, I have tested the released version in my minecraft server and I am sure there's no serious problem in these versions. If a really serious bug, like the one you met that prevents player to mine charged certus quartz, exists, I think someone would point it out much earlier. 

I won't totally give up this project. But right now I really do not have enough time for anything except study. I would appreciate it if you could understand me.

**Comment by JoeSGT** [comment]
i had revert this commit https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/d050451bce40c9a4c0f9f78117bb5215592bc950 and test it and it seem it's this commit that made the crash when i use this commit i crash

**Comment by JoeSGT** [comment]
And also i do understand no worries this is an old version of MC so im even shock to see that there a much better fixed of ae2 for 1.7 that you provided and i thanks you for that
